# Generated by Django 4.0.4 on 2022-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_no',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
