# Generated by Django 4.0.4 on 2022-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='my_room_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
