# Generated by Django 4.0.4 on 2022-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phn_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
