# Generated by Django 4.0.4 on 2022-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contact_phn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
