# Generated by Django 4.0.4 on 2022-07-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_managers_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('accounts.user',),
        ),
    ]
