# Generated by Django 4.0.4 on 2022-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
