# Generated by Django 4.0.4 on 2022-07-12 10:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=accounts.models.pass_gen, max_length=8),
        ),
    ]
