# Generated by Django 4.0.4 on 2022-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, default='user1.jpg', null=True, upload_to='documents'),
        ),
    ]
